const articles=[
{id:'xpeng',title:'小鹏 IRON 完成自动化总装，机器人生产线正式启用',summary:'IT之家报道，小鹏机器人生产线于9月8日正式启用，首台高阶通用人形机器人完成自动化总装并自主走下产线。IRON计划从门店和园区等商业场景开始落地。',categories:['人形'],scenes:['商用服务'],event:'新品',date:'2026-09-08',source:'IT之家',url:'https://www.ithome.com/0/999/529.htm',image:''},
{id:'hand',title:'灵巧手的下一场竞争：从自由度，走向真实任务',summary:'36氪采访星际光年，关注绳驱灵巧手的工程化：将电机移出手指，结合张力补偿、触觉与记忆模型，尝试解决长期运行中的磨损、控制精度与稳定性问题。',categories:['灵巧手','算法','零部件'],scenes:['工业制造'],event:'技术',date:'2026-07-28',source:'36氪',url:'https://www.36kr.com/p/3913717424182400',image:''},
{id:'weld',title:'群青智能获近亿元融资，让工业机器人学会柔性焊接',summary:'群青智能获得赛智伯乐、杭州高新金投、东方富海共同支持。公司从焊接场景切入，利用真实工艺数据与物理AI模型，探索复杂工业现场的柔性作业。',categories:['AI','算法','数据'],scenes:['工业制造'],event:'融资',date:'2026-06-26',source:'36氪',url:'https://www.36kr.com/p/3868375587034114',image:''},
{id:'joint',title:'航墨科技获近亿元天使轮融资，押注可变刚度关节',summary:'航墨科技专注智能变刚度关节与消费级外骨骼，将近亿元融资用于研发及市场推广。团队围绕人形、机械臂等形态，探索工业、消费与医疗康复等场景。',categories:['零部件'],scenes:['工业制造','医疗健康'],event:'融资',date:'2026-07-01',source:'36氪 · 硬氪',url:'https://www.36kr.com/p/3877060559433984',image:''},
{id:'home',title:'未来不远获10亿元融资，轮式机器人走进家庭',summary:'36氪专访未来不远创始人张翼：公司采用轮式底盘与双机械臂，机器人已进入上海约500个家庭，探索陪伴、简单家务和宠物照料等任务。',categories:['轮式','复合','AI'],scenes:['家庭服务'],event:'融资',date:'2026-08-24',source:'36氪 · 硬氪',url:'https://www.36kr.com/p/3952867368648073',image:''},
{id:'vision',title:'梅卡曼德登陆港交所，机器人“眼脑手”迎来上市节点',summary:'梅卡曼德于9月1日在港交所上市，本次发行募资约23.5亿港元。募集资金计划投向研发、全球业务拓展、产品组合、产能及运营等方向。',categories:['AI','算法','零部件'],scenes:['工业制造'],event:'上市',date:'2026-09-01',source:'36氪 · 雷帝触网',url:'https://www.36kr.com/p/3964347992612356',image:''},
{id:'unitree',title:'宇树科技上市前夕：从机器人产品，走向资本市场',summary:'这篇8月18日的报道回顾了宇树的发行安排、股东构成与经营表现，为理解机器人企业的商业化提供了一个观察样本。',categories:['人形','四足'],scenes:['科研教育'],event:'上市',date:'2026-08-18',source:'36氪 · 雷帝触网',url:'https://www.36kr.com/p/3943635088374915',image:'https://img.36krcdn.com/hsossms/20260817/v2_0ff41b8e7ac4497f8f1212212374baf3@000000@ai_oswg297328oswg1536oswg722_img_000~tplv-1marlgjv7f-ai-v3:600:400:600:400:q70.jpg'}];
let state={category:'全部',scene:'全部',event:null,query:'',sort:'recommended',limit:5};
const categories=['全部','人形','轮式','四足','履带','复合','灵巧手','协作臂','AI','算法','数据','零部件'];const scenes=['全部','工业制造','商用服务','科研教育','家庭服务','农业服务','特种作业','医疗健康','养老服务'];const events=['政策','新品','融资','上市','技术','活动'];
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function filters(id,items,key){const el=document.getElementById(id);items.forEach(item=>{const b=document.createElement('button');b.textContent=item;b.className=item==='全部'?'active':'';b.setAttribute('aria-pressed',item==='全部');b.onclick=()=>{state[key]=key==='event'&&state[key]===item?null:item;state.limit=5;el.querySelectorAll('button').forEach(x=>{const selected=x.textContent===state[key];x.classList.toggle('active',selected);x.setAttribute('aria-pressed',selected)});render()};el.append(b)})}
function safeImage(a){return a.image||'assets/logo.svg'}
function render(){let found=articles.filter(a=>(state.category==='全部'||a.categories.includes(state.category))&&(state.scene==='全部'||a.scenes.includes(state.scene))&&(!state.event||a.event===state.event)&&[a.title,a.summary,a.source,a.event,...a.categories,...a.scenes].join(' ').toLowerCase().includes(state.query.toLowerCase()));if(state.sort==='latest')found.sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('count').textContent=`${found.length} 篇精选`;document.getElementById('feed').innerHTML=found.length?found.slice(0,state.limit).map(a=>`<article class="news-card"><a class="news-image" href="${a.url}" target="_blank" rel="noopener noreferrer" aria-label="阅读：${a.title}"><img src="${safeImage(a)}" alt="${a.title}，图片来自原报道" loading="lazy"></a><div class="news-body"><div class="news-tags"><span>${a.categories[0]}</span><span>${a.scenes[0]}</span><span>${a.event}</span></div><h3><a href="${a.url}" target="_blank" rel="noopener noreferrer">${a.title}</a></h3><p>${a.summary}</p><div class="news-meta"><span class="source-logo">${a.source==='IT之家'?'IT':'36'}</span><span>${a.source}</span><time datetime="${a.date}">${a.date}</time><a href="${a.url}" target="_blank" rel="noopener noreferrer">阅读全文 ↗</a></div></div></article>`).join(''):`<div class="empty"><h3>暂未收录相关资讯</h3><p>试试其他类别、场景、事件，或更简短的关键词。</p><button id="reset">清除筛选</button></div>`;const more=document.getElementById('more');more.disabled=found.length<=state.limit;more.textContent=more.disabled?'已展示全部精选资讯':'查看更多资讯 ＋';document.getElementById('reset')?.addEventListener('click',reset);imageFallbacks()}
function imageFallbacks(){document.querySelectorAll('#news-view img').forEach(img=>{img.onerror=()=>{img.onerror=null;img.src='assets/logo.svg';img.style.objectFit='contain';img.alt='Robot Galaxy 机器人标识（原报道图片暂不可用）'}})}
function renderSpots(){document.getElementById('spotlights').innerHTML=articles.slice(0,3).map((a,i)=>`<a class="spotlight" href="${a.url}" target="_blank" rel="noopener noreferrer"><img src="${safeImage(a)}" alt="${a.title}，图片来自原报道"><div class="spot-top"><span class="badge ${i===0?'blue':''}">${['焦点关注','技术前沿','产业动态'][i]}</span>${i===0?'<span class="badge">人形机器人</span>':''}</div><div class="spot-content"><h2>${["走下产线，走向现实。<br>小鹏 IRON 的量产时刻",'灵巧手，开始比拼<br>真实世界的工作能力','AI + 工业焊接<br>资本关注真实落地'][i]}</h2>${i===0?'<p>从门店到园区，人形机器人探索商业场景。</p>':''}<div class="spot-meta"><span>${a.source} · ${a.date.slice(5).replace('-','.')}</span><span>↗</span></div></div></a>`).join('');imageFallbacks()}
function reset(){state={...state,category:'全部',scene:'全部',event:null,query:'',limit:5};document.getElementById('search').value='';document.querySelectorAll('#news-view .filter-row button').forEach(b=>{const active=b.textContent==='全部';b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});render()}
const modules={'资讯':['行业新闻、研究报告与活动，理解机器人产业的每一步。',['机器人资讯','机器人研报','机器人活动']],'产品':['建立机器人产业的数据底座，让产品参数和厂商信息更容易查询与比较。',['机器人数据库','厂商档案','机器人榜单','产品对比']],'测评':['从实验室到真实场景，了解机器人实际表现。',['专业测评','真实用户评价','产品 PK']],'社区':['连接从业者、工程师与机器人爱好者。',['话题讨论','案例分享','问答与交流']],'机器人买卖':['围绕真实采购需求，连接厂商、经销商与集成商。',['产品询价','多供应商报价','采购需求大厅']],'解决方案':['从具体场景出发，寻找合适的机器人与服务团队。',['演出与活动','教育与夏令营','场景方案撮合']],'AI 互动':['让自然语言成为探索机器人产业的新入口。',['AI 搜索','选型顾问','研报助手','场景咨询']],'机器人研报':['面向从业者、投资人与采购方的机器人知识库。',['研报筛选','核心结论','赛道知识地图']],'机器人活动':['发现机器人行业展会、论坛、技术沙龙与线下交流。',['活动日历','机器人总动员','直播与回放']]};
const dialog=document.getElementById('module-dialog');function openModule(name){if(name==='首页'){window.showHome();return}if(name==='厂商档案'){window.showManufacturers();return}if(name==='机器人买卖'){window.showMarket();return}if(name==='社区'){window.showCommunity();return}if(name==='测评'){window.showReviews();return}if(name==='产品对比'){window.showCompare();return}if(name==='机器人榜单'){window.showRankings();return}if(name==='产品'||name==='机器人数据库'){window.showProducts();return}if(name==='机器人活动'){window.showEvents();return}if(name==='机器人研报'){window.showReports();return}if(name==='机器人资讯'){window.showNews();reset();document.getElementById('news').scrollIntoView({behavior:'smooth'});return}const [copy,options]=modules[name]||['该模块正在规划中。',[]];document.getElementById('module-title').textContent=name;document.getElementById('module-copy').textContent=copy;const list=document.getElementById('module-options');list.replaceChildren();options.forEach(o=>{const e=document.createElement(name==='资讯'?'button':'span');e.textContent=o;if(name==='资讯')e.onclick=()=>{dialog.close();openModule(o)};list.append(e)});dialog.showModal()}
document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>openModule(b.dataset.module));document.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>openModule(b.dataset.channel));document.querySelector('.close').onclick=()=>dialog.close();document.getElementById('back-news').onclick=()=>{dialog.close();window.showNews();document.getElementById('news').scrollIntoView({behavior:'smooth'})};dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.getElementById('search').addEventListener('input',e=>{if(location.hash!=='#news')return;state.query=e.target.value.trim();state.limit=5;render()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!dialog.open){e.preventDefault();document.getElementById('search').focus()}});document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{state.sort=b.dataset.sort;document.querySelectorAll('[data-sort]').forEach(x=>x.classList.toggle('current',x===b));render()});document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{reset();state.query=b.dataset.topic;document.getElementById('search').value=state.query;render();document.getElementById('news').scrollIntoView({behavior:'smooth'})});document.getElementById('more').onclick=()=>{state.limit+=5;render()};filters('categories',categories,'category');filters('scenes',scenes,'scene');filters('events',events,'event');document.getElementById('reset-filters').onclick=reset;
fetch('images.json').then(r=>{if(!r.ok)throw Error('image metadata unavailable');return r.json()}).then(images=>{articles.forEach(a=>{if(images[a.id])a.image=images[a.id]});renderSpots();render()}).catch(()=>{renderSpots();render()});

window.homeNews=()=>articles[0];
