(()=>{
const $=id=>document.getElementById(id),e=escapeHtml;
let records=[],query='';
const view=document.createElement('main');view.id='events-view';view.className='wrap';view.hidden=true;
view.innerHTML=`<section class="events-heading"><div><p class="eyebrow">ROBOT GALAXY / EVENTS</p><h1>机器人行业，期待你的声音<span>。</span></h1><p>从行业现场，到一场聊得深入的沙龙。</p></div><span>信息核对于 2026.09.14</span></section><section class="salon-feature"><a class="salon-poster" href="events/salon-september.jpg" target="_blank" aria-label="查看机器人总动员完整海报及报名二维码"><img src="events/salon-september.jpg" alt="机器人总动员：家庭机器人，先过有用这关，9月18日北京沙龙海报"></a><div class="salon-copy"><div class="salon-kicker">机器人总动员 <span>VOL.01 · 家庭机器人专场</span></div><h2>家庭机器人，<br>先过<span>“有用”</span>这关</h2><p>今晚只聊能落地的真话。围绕家庭机器人的真实用途与落地展开交流，不聊科幻，关起门说真话。</p><dl><div><dt>时间</dt><dd><time datetime="2026-09-18T19:30:00+08:00">2026.09.18 周五 · 19:30—21:30</time></dd></div><div><dt>地点</dt><dd>北京 · 石景山 · 首钢园</dd></div><div><dt>票价</dt><dd><strong>¥58</strong> / 人 <small>包含简餐、饮品等</small></dd></div></dl><div class="salon-links"><a id="salon-booking" class="event-primary" href="https://hdxu.cn/EAySQ" target="_blank" rel="noopener noreferrer">活动行报名 · ¥58 ↗</a><a id="salon-intro" href="https://www.xiaohongshu.com/explore/6aa512ee000000002802c0de?xsec_token=CB2S2Pv_LmFgOw8UFZr4rxM-vjX26biozdsbhjK4N7uUU=&xsec_source=app_share" target="_blank" rel="noopener noreferrer">小红书活动介绍 ↗</a></div><small class="salon-note">活动行报名 · 具体集合位置以报名页或主办方通知为准</small></div></section><section class="industry-events"><div class="section-heading"><h2><i></i>中国机器人行业活动 <span>INDUSTRY EVENTS</span></h2><span id="event-count"></span></div><div id="event-list" aria-live="polite">正在读取活动…</div></section><p class="source-note event-foot">时间均为北京时间。活动安排、余票与价格以主办方最新信息为准；本站提供官方入口，购票与报名在对应平台完成。</p>`;
$('reports-view').after(view);
function route(){const active=location.hash==='#events';view.hidden=!active;if(active){$('news-view').hidden=true;$('reports-view').hidden=true;document.querySelectorAll('[data-channel]').forEach(b=>b.classList.toggle('selected',b.dataset.channel==='机器人活动'));document.querySelectorAll('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module==='资讯'));$('search').placeholder='搜索活动、城市、关键词';$('search').setAttribute('aria-label','搜索活动');$('search').value=query;}}
window.showEvents=()=>{location.hash='events';route()};window.addEventListener('hashchange',route);route();
function renderEvents(){const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date());const found=records.filter(r=>[r.title,r.city,r.venue,r.summary,r.type].join(' ').toLowerCase().includes(query.toLowerCase()));$('event-count').textContent=found.length+' 场活动';const card=r=>{const past=r.end<today;return `<article class="event-card"><div class="event-date"><span>${r.start.slice(0,4)} / ${r.start.slice(5,7)}</span><strong>${r.start.slice(8)}</strong><small>— ${r.end.slice(5).replace('-','.')}</small></div><div class="event-body"><div class="event-labels"><span>${e(r.type)}</span><span>${past?'已结束':r.start<=today?'进行中':'即将举办'}</span></div><h3><a href="${e(r.url)}" target="_blank" rel="noopener noreferrer">${e(r.title)}</a></h3><div class="event-place">${e(r.city)} · ${e(r.venue)}</div><p>${e(r.summary)}</p><div class="event-card-bottom"><a href="${e(r.source)}" target="_blank" rel="noopener noreferrer">信息来源 ↗</a><a class="event-action" href="${e(r.url)}" target="_blank" rel="noopener noreferrer">${past?'官网回顾':e(r.action)} ↗</a></div>${!past?`<small class="event-ticket-note">${e(r.note)}</small>`:''}</div></article>`};const upcoming=found.filter(r=>r.end>=today).sort((a,b)=>a.start.localeCompare(b.start));const past=found.filter(r=>r.end<today).sort((a,b)=>b.start.localeCompare(a.start));$('event-list').innerHTML=found.length?(upcoming.length?`<h3 class="event-group-heading">即将举办 / 进行中</h3><div class="event-grid">${upcoming.map(card).join('')}</div>`:'')+(past.length?`<h3 class="event-group-heading">往届活动</h3><div class="event-grid past-events">${past.map(card).join('')}</div>`:''):`<div class="empty"><h3>暂无匹配的行业活动</h3><p>试试“上海”“机器人”或“ROS”。</p><button id="clear-event-search">清除搜索</button></div>`;$('clear-event-search')?.addEventListener('click',()=>{query='';$('search').value='';renderEvents()})}
$('search').addEventListener('input',x=>{if(!view.hidden){query=x.target.value.trim();renderEvents()}});
fetch('events/catalog.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{records=data;renderEvents()}).catch(()=>{$('event-list').textContent='活动目录暂时无法读取，请刷新重试。'});
})();
