(()=>{
const $=id=>document.getElementById(id),e=escapeHtml;
const view=document.createElement('main');view.id='home-view';view.className='wrap';view.hidden=true;$('news-view').before(view);
const active=()=>!location.hash||location.hash==='#home';
const slideInfo=[['机器人资讯','NEWS','#news'],['机器人研报','RESEARCH','#reports'],['机器人活动','EVENTS','#events'],['机器人测评','REVIEWS','#reviews'],['机器人社区','COMMUNITY','#community']];
const sections=[
{title:'资讯',en:'INSIGHTS',copy:'发现正在发生的事，看见产业背后的逻辑。',links:[['机器人资讯','机器人世界，正在发生。','#news'],['机器人研报','从本体到核心零部件，理解产业脉络。','#reports'],['机器人活动','机器人行业，期待你的声音。','#events']]},
{title:'产品',en:'DATABASE',copy:'从形态出发，认识每一种机器人可能。',links:[['机器人数据库','探索形态、型号与核心参数。','#products'],['厂商档案','连接核心技术、零部件与整机厂商。','#products/manufacturers'],['机器人榜单','发现值得关注的机器人。','#products/rankings'],['产品对比','把差异放在一起，让选择更清晰。','#products/compare']]},
{title:'测评',en:'HANDS-ON',copy:'从参数走进现场，看见真实表现。',links:[['视频测评','直观感受机器人如何工作。','#reviews'],['文章测评','读懂功能、体验与使用细节。','#reviews']]},
{title:'社区',en:'COMMUNITY',copy:'机器人同好，在这里相遇。',links:[['机器人社区','分享你的发现、体验与日常。','#community']]},
{title:'机器人买卖',en:'MARKETPLACE',copy:'选一台机器人，开启更多可能。',links:[['机器人选购','从型号到配置，让选购更清晰。','#market']]},
{title:'解决方案',en:'SOLUTIONS',copy:'从一个真实场景，走向一个可行方案。',pending:true,links:[['场景方案撮合','连接应用需求与解决方案服务商。','解决方案']]},
{title:'AI 互动',en:'GALAXY INTELLIGENCE',copy:'用一个问题，打开机器人世界。',pending:true,links:[['AI 助手','探索行业、比较产品、寻找选型思路。','AI 互动']]}
];
let index=0,timer=null,paused=false,hover=false,focused=false,q='',startX=null;
function feature(i){const base={label:slideInfo[i][0],en:slideInfo[i][1],route:slideInfo[i][2],title:slideInfo[i][0],summary:'探索这一板块的内容与发现。',image:'assets/logo.svg',meta:'ROBOT GALAXY',fit:'contain'};
if(i===0){const r=window.homeNews?.();if(r)Object.assign(base,{title:r.title,summary:r.summary,image:r.image||'assets/logo.svg',meta:r.source+' · '+r.date,fit:r.image?'cover':'contain'})}
if(i===1){const r=window.homeReport?.();if(r)Object.assign(base,{title:r.title,summary:r.summary,image:r.cover||'assets/logo.svg',meta:r.institution+' · '+(r.date||r.period||'收录研报')})}
if(i===2)Object.assign(base,{title:'家庭机器人，先过“有用”这关',summary:'机器人总动员 VOL.01 · 今晚只聊能落地的真话。围绕家庭机器人的真实用途与落地展开交流。',image:'events/salon-september.jpg',meta:'2026.09.18 · 北京首钢园 · ¥58 / 人'});
if(i===3){const r=window.homeReview?.();if(r)Object.assign(base,{title:r.title,summary:r.summary,image:r.image,meta:r.platform+' · '+r.author+' · '+r.date,fit:'cover'})}
if(i===4){const r=window.homeCommunity?.();if(r)Object.assign(base,{title:r.title,summary:r.body,image:r.images?.[0]||'assets/logo.svg',meta:r.author+' · '+r.topic,note:r.demo?'示例话题 · 欢迎加入讨论':'本浏览器保存的社区笔记'})}
return base}
function render(){view.innerHTML=`<section class="home-carousel" aria-roledescription="轮播图" aria-label="五大模块精选内容" tabindex="0"><div id="home-slide"></div><div class="home-carousel-controls"><div class="home-dots" aria-label="选择轮播内容">${slideInfo.map((s,i)=>`<button data-home-slide="${i}" aria-label="切换到${s[0]}" aria-pressed="${i===index}"></button>`).join('')}</div><button id="home-pause" aria-label="暂停自动轮播">Ⅱ</button></div></section><section class="home-directory"><div class="home-directory-heading"><div><p class="eyebrow">EXPLORE THE GALAXY</p><h2>连接每一种机器人可能<span>。</span></h2></div><span>发现 · 理解 · 选择 · 连接</span></div><div id="home-sections" class="home-sections"></div></section>`;
const carousel=view.querySelector('.home-carousel');carousel.addEventListener('pointerenter',ev=>{if(ev.pointerType!=='touch'){hover=true;schedule()}});carousel.addEventListener('pointerleave',()=>{hover=false;schedule()});carousel.addEventListener('focusin',()=>{focused=true;schedule()});carousel.addEventListener('focusout',ev=>{if(!carousel.contains(ev.relatedTarget)){focused=false;schedule()}});carousel.addEventListener('pointerdown',ev=>{if(ev.pointerType==='touch')startX=ev.clientX});carousel.addEventListener('pointerup',ev=>{if(startX!==null&&Math.abs(ev.clientX-startX)>45){change(ev.clientX<startX?1:-1)}startX=null});carousel.addEventListener('pointercancel',()=>{startX=null});carousel.addEventListener('keydown',ev=>{if(ev.key==='ArrowRight'||ev.key==='ArrowLeft'){ev.preventDefault();change(ev.key==='ArrowRight'?1:-1)}});$('home-pause').onclick=()=>{paused=!paused;schedule()};view.querySelectorAll('[data-home-slide]').forEach(b=>b.onclick=()=>{index=Number(b.dataset.homeSlide);draw();schedule()});draw();directory();schedule()}
function draw(){const f=feature(index);$('home-slide').innerHTML=`<article class="home-feature"><div class="home-feature-copy"><p class="home-feature-kicker"><span>${e(f.label)}</span> ${f.en}</p><p class="home-feature-meta">${e(f.meta)}</p><h1><a href="${f.route}">${e(f.title)}</a></h1><p class="home-feature-summary">${e(f.summary)}</p>${f.note?`<small class="home-feature-note">${e(f.note)}</small>`:''}<a class="home-feature-link" href="${f.route}">进入${e(f.label)} <span>↗</span></a></div><a class="home-feature-art ${f.fit==='cover'?'photo':'document'}" href="${f.route}" aria-label="进入${e(f.label)}：${e(f.title)}"><img src="${e(f.image)}" alt="${e(f.title)}" style="object-fit:${f.fit}" onerror="this.onerror=null;this.src='assets/logo.svg';this.style.objectFit='contain'"></a></article>`;view.querySelectorAll('[data-home-slide]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)))}
function change(delta){index=(index+delta+slideInfo.length)%slideInfo.length;draw();schedule()}
function schedule(){clearInterval(timer);timer=null;const running=active()&&!paused&&!hover&&!focused&&!document.hidden;view.classList.toggle('home-playing',running);if($('home-pause')){$('home-pause').textContent=paused?'▷':'Ⅱ';$('home-pause').setAttribute('aria-label',paused?'继续自动轮播':'暂停自动轮播')};if(running)timer=setInterval(()=>{index=(index+1)%slideInfo.length;draw()},3000)}
function directory(){const found=sections.filter(s=>[s.title,s.copy,...s.links.flat()].join(' ').toLowerCase().includes(q.trim().toLowerCase()));$('home-sections').innerHTML=found.length?found.map(s=>`<article class="home-module ${['资讯','产品'].includes(s.title)?'wide':''}"><div class="home-module-heading"><span>${s.en}</span>${s.pending?'<small>即将开放</small>':'<b>↗</b>'}</div><h3>${s.title}</h3><p>${s.copy}</p><div class="home-module-links">${s.links.map(([title,copy,href])=>href.startsWith('#')?`<a href="${href}"><span><strong>${title}</strong><small>${copy}</small></span><b>→</b></a>`:`<button data-home-module="${href}"><span><strong>${title}</strong><small>${copy}</small></span><b>→</b></button>`).join('')}</div></article>`).join(''):'<div class="home-no-results">没有找到相关模块，试试“研报”“厂商”或“对比”。</div>';view.querySelectorAll('[data-home-module]').forEach(b=>b.onclick=()=>openModule(b.dataset.homeModule))}
function route(){view.hidden=!active();clearInterval(timer);if(active()){['news-view','reports-view','events-view','products-view','reviews-view','community-view','market-view'].forEach(id=>{if($(id))$(id).hidden=true});document.querySelectorAll('header>.subnav').forEach(el=>el.hidden=true);document.querySelectorAll('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module==='首页'));$('search').placeholder='搜索模块或功能，如研报、厂商、对比';$('search').setAttribute('aria-label','搜索首页模块');$('search').value=q;hover=false;focused=false;render()}}
$('search').addEventListener('input',ev=>{if(active()){q=ev.target.value;directory()}});document.addEventListener('visibilitychange',schedule);window.addEventListener('hashchange',route);window.showHome=()=>{location.hash='home';route();window.scrollTo({top:0,behavior:'smooth'})};route();
})();
