(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host,data,status='loading',stage='全部',category='全部',segment='全部',query='',page=1;
const active=()=>location.hash==='#products/manufacturers';
const cats=()=>[...new Set(data.groups.filter(g=>stage==='全部'||g.stage===stage).map(g=>g.category))];
function matches(f){return f.categories.some(id=>{const g=data.groups.find(g=>g.id===id);return(stage==='全部'||g.stage===stage)&&(category==='全部'||g.category===category)&&(segment==='全部'||g.id===segment)})&&f.name.toLowerCase().includes(query.trim().toLowerCase())}
function countCategory(c,s){return data.firms.filter(f=>f.categories.some(id=>{const g=data.groups.find(g=>g.id===id);return g.category===c&&g.stage===s})).length}
function choose(s,c='全部',seg='全部'){stage=s;category=c;segment=seg;page=1;display()}
function display(){if(!host||!active())return;const search=$('search');search.placeholder='搜索厂商或机构名称';search.setAttribute('aria-label','搜索厂商或机构名称');search.value=query;
if(!data){host.innerHTML=`<div class="vendor-empty"><h2>${status==='failed'?'暂时无法读取厂商档案':'正在整理厂商档案…'}</h2>${status==='failed'?'<button id="vendor-retry">重新加载</button>':''}</div>`;$('vendor-retry')?.addEventListener('click',load);return}
host.innerHTML=`<section class="vendor-heading"><div><p class="eyebrow">ROBOT GALAXY / MANUFACTURERS</p><h1>厂商档案<span>。</span></h1><p>从核心零部件到机器人整机，按产业环节发现厂商。</p></div><div class="vendor-totals"><strong>${data.firms.length}<small>家企业及机构</small></strong><strong>${data.groups.length}<small>个细分领域</small></strong></div></section><div class="vendor-source"><span>首批来源：${esc(data.source.title)} · 第 4–5 页</span><a href="manufacturers/source-4.png" target="_blank" rel="noopener">上游原图 ↗</a><a href="manufacturers/source-5.png" target="_blank" rel="noopener">中游原图 ↗</a></div><div class="vendor-stages" aria-label="产业链环节">${['全部','上游','中游'].map(s=>`<button data-vendor-stage="${s}" aria-pressed="${s===stage}">${s==='全部'?'全产业链':s==='上游'?'上游 · 核心技术与零部件':'中游 · 机器人整机'}</button>`).join('')}</div><div class="vendor-layout"><aside class="vendor-sidebar" aria-label="厂商分类"><button class="vendor-all ${category==='全部'?'chosen':''}" data-vendor-all>全部分类</button>${['上游','中游'].filter(s=>stage==='全部'||s===stage).map(s=>`<h2>${s==='上游'?'上游 / 核心技术与零部件':'中游 / 机器人整机'}</h2>${[...new Set(data.groups.filter(g=>g.stage===s).map(g=>g.category))].map(c=>`<button data-vendor-category="${esc(c)}" data-stage="${s}" aria-pressed="${category===c}"><span>${esc(c)}</span><small>${countCategory(c,s)}</small></button>`).join('')}`).join('')}</aside><section class="vendor-main"><div class="vendor-filter"><div class="vendor-filter-top"><h2>${category==='全部'?(stage==='全部'?'全部厂商':stage+'厂商'):esc(category)}</h2><label><input id="vendor-query" type="search" aria-label="搜索厂商名称" placeholder="搜索厂商名称" value="${esc(query)}"></label></div>${category!=='全部'&&data.groups.filter(g=>g.category===category).length>1?`<div class="vendor-segments" aria-label="细分领域"><button data-vendor-segment="全部" aria-pressed="${segment==='全部'}">全部细分</button>${data.groups.filter(g=>g.category===category&&(stage==='全部'||g.stage===stage)).map(g=>`<button data-vendor-segment="${g.id}" aria-pressed="${segment===g.id}">${esc(g.segment)}</button>`).join('')}</div>`:''}<p>按图谱分类整理；同一企业可归属多个领域。收录范围含分支机构，不代表全国完整名录。</p></div><div id="vendor-results"></div></section></div><dialog id="vendor-dialog" aria-labelledby="vendor-dialog-title"><button class="vendor-close" aria-label="关闭厂商档案">×</button><div id="vendor-dialog-content"></div></dialog>`;
host.querySelectorAll('[data-vendor-stage]').forEach(b=>b.onclick=()=>choose(b.dataset.vendorStage));$('vendor-query').oninput=e=>{query=e.target.value;$('search').value=query;page=1;results()};host.querySelector('[data-vendor-all]').onclick=()=>choose(stage);host.querySelectorAll('[data-vendor-category]').forEach(b=>b.onclick=()=>choose(b.dataset.stage,b.dataset.vendorCategory));host.querySelectorAll('[data-vendor-segment]').forEach(b=>b.onclick=()=>choose(stage,category,b.dataset.vendorSegment));host.querySelector('.vendor-close').onclick=()=>$('vendor-dialog').close();results()}
function tags(f){return f.categories.map(id=>data.groups.find(g=>g.id===id))}
function results(){const found=data.firms.filter(matches);const max=Math.max(1,Math.ceil(found.length/24));page=Math.min(page,max);$('vendor-results').innerHTML=`<div class="vendor-result-heading" role="status"><strong>${found.length} 家企业及机构</strong><span>${found.length?`第 ${(page-1)*24+1}–${Math.min(page*24,found.length)} 家`:''}</span></div>${found.length?`<div class="vendor-grid">${found.slice((page-1)*24,page*24).map(f=>{const ts=tags(f);return `<article class="vendor-card"><div class="vendor-card-top"><span class="vendor-monogram" aria-hidden="true">${esc(f.name.slice(0,2))}</span><span class="vendor-chain">${[...new Set(ts.map(g=>g.stage))].join(' / ')}</span></div><h3>${esc(f.name)}</h3><div class="vendor-tags">${ts.slice(0,4).map(g=>`<span>${esc(g.category===g.segment?g.category:g.category+' · '+g.segment)}</span>`).join('')}${ts.length>4?`<span>+${ts.length-4} 个领域</span>`:''}</div><div class="vendor-card-bottom"><small>图谱第 ${f.pages.join('、')} 页${f.branch?' · 分支机构':''}</small><button data-vendor-open="${f.id}" aria-label="查看${esc(f.name)}的图谱档案">查看档案 ↗</button></div></article>`}).join('')}</div><nav class="vendor-pagination" aria-label="厂商列表分页"><button id="vendor-prev" ${page===1?'disabled':''}>← 上一页</button><span>${page} / ${max}</span><button id="vendor-next" ${page===max?'disabled':''}>下一页 →</button></nav>`:`<div class="vendor-empty"><h3>${segment!=='全部'&&!data.groups.find(g=>g.id===segment).names.length?'该领域暂无具名厂商':'没有匹配的厂商'}</h3><p>${segment!=='全部'&&!data.groups.find(g=>g.id===segment).names.length?'原图保留了这一分类，但未列出厂商名称。':'试试其他分类，或清空关键词。'}</p><button id="vendor-clear">重置筛选</button></div>`}`;
$('vendor-clear')?.addEventListener('click',()=>{query='';choose('全部')});$('vendor-prev')?.addEventListener('click',()=>{page--;results();$('vendor-results').scrollIntoView({block:'start'})});$('vendor-next')?.addEventListener('click',()=>{page++;results();$('vendor-results').scrollIntoView({block:'start'})});host.querySelectorAll('[data-vendor-open]').forEach(b=>b.onclick=()=>openFirm(b.dataset.vendorOpen))}
function openFirm(id){const f=data.firms.find(f=>f.id===id);$('vendor-dialog-content').innerHTML=`<p class="eyebrow">INDUSTRY PROFILE</p><h2 id="vendor-dialog-title">${esc(f.name)}</h2><p class="vendor-profile-note">${f.branch?'原图以分支机构标记收录。':'名称与分类按原图收录。'}本页先展示产业分类档案。</p><h3>所属产业领域</h3><ul class="vendor-memberships">${tags(f).map(g=>`<li><span>${g.stage}</span><div><strong>${esc(g.category)}</strong>${g.category!==g.segment?`<p>${esc(g.segment)}</p>`:''}</div><a href="manufacturers/source-${g.page}.png" target="_blank" rel="noopener">第 ${g.page} 页 ↗</a></li>`).join('')}</ul><p class="vendor-profile-note">来源：${esc(data.source.title)}。分类不等同于当前在售产品或经核验的供货能力；公司简介、官网和联系方式后续补充。</p>`;$('vendor-dialog').showModal()}
async function load(){status='loading';display();try{const r=await fetch('manufacturers/catalog.json');if(!r.ok)throw Error();data=await r.json();status='ready'}catch{status='failed'}display()}
window.renderManufacturers=el=>{host=el;display()};window.showManufacturers=()=>{location.hash='products/manufacturers';if(host)display()};$('search').addEventListener('input',e=>{if(active()&&data){query=e.target.value;$('vendor-query').value=query;page=1;results()}});load();if(active()){host=$('products-view');document.querySelectorAll('[data-product-module]').forEach(b=>b.classList.toggle('selected',b.dataset.productModule==='厂商档案'));display()}
})();
