(()=>{
const $=id=>document.getElementById(id);
const items=[
['all','全部','ALL ROBOTS','探索全部机器人形态与操作部件','<rect x="8" y="8" width="18" height="18" rx="3"/><rect x="38" y="8" width="18" height="18" rx="3"/><rect x="8" y="38" width="18" height="18" rx="3"/><rect x="38" y="38" width="18" height="18" rx="3"/>'],
['humanoid','人形','HUMANOID','以类人形态感知、移动与执行任务','<rect x="24" y="5" width="16" height="14" rx="4"/><path d="M24 26h16l4 16H20l4-16ZM20 28 10 39m34-11 10 11M25 42l-5 16m19-16 5 16M29 12h6"/>'],
['wheeled','轮式','WHEELED','依靠轮式底盘实现灵活移动','<rect x="17" y="12" width="30" height="30" rx="6"/><path d="M25 23h14M32 12V6M18 46h28"/><circle cx="18" cy="49" r="7"/><circle cx="46" cy="49" r="7"/>'],
['quadruped','四足','QUADRUPED','四足支撑，适应多种地形','<path d="M14 23h32v15H14zM46 25l9-5v12h-9M17 38l-5 12 5 8m24-20 6 12-4 8M23 38l4 16m9-16-3 16M8 19l6 7"/>'],
['tracked','履带','TRACKED','连续履带行走，关注通过性与稳定性','<rect x="7" y="35" width="50" height="21" rx="10"/><circle cx="19" cy="45" r="4"/><circle cx="32" cy="45" r="4"/><circle cx="45" cy="45" r="4"/><path d="M18 35V21h28v14M25 21V12h14v9M32 12V6"/>'],
['hybrid','复合','MOBILE MANIPULATOR','移动底盘与操作机构相结合','<rect x="10" y="42" width="44" height="12" rx="4"/><circle cx="19" cy="56" r="3"/><circle cx="45" cy="56" r="3"/><path d="M27 42V31l14-13-9-10M35 8h-8v8m14 2 10 6 5-5M19 48h9"/><circle cx="27" cy="31" r="4"/><circle cx="41" cy="18" r="4"/>'],
['hand','灵巧手','DEXTEROUS HAND','多指协同，完成精细抓取与操作','<path d="M21 33V14a3 3 0 0 1 6 0v16-21a3 3 0 0 1 6 0v21-19a3 3 0 0 1 6 0v19-13a3 3 0 0 1 6 0v24c0 9-6 15-15 15-8 0-11-5-14-10l-6-10a4 4 0 0 1 6-5l5 5M26 56v5m13-6v6"/>'],
['cobot','协作臂','COLLABORATIVE ARM','面向人机协作的机械臂','<path d="M14 57h36M21 57v-9h20v9M28 48 16 31l17-16 14 12M43 31l6 7 8-7-6-7"/><circle cx="16" cy="31" r="5"/><circle cx="33" cy="15" r="5"/><circle cx="47" cy="27" r="4"/>']
];
const icon=p=>`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`;
const view=document.createElement('main');view.id='products-view';view.className='wrap';view.hidden=true;$('events-view').after(view);
const sub=document.createElement('div');sub.className='subnav product-subnav';sub.hidden=true;sub.innerHTML='<div class="wrap"><button class="selected" data-product-module="机器人数据库">机器人数据库</button><button data-product-module="厂商档案">厂商档案</button><button data-product-module="机器人榜单">机器人榜单</button><button data-product-module="产品对比">产品对比</button><span>认识形态 · 探索产品</span></div>';document.querySelector('header').append(sub);sub.querySelectorAll('button').forEach(b=>b.onclick=()=>b.dataset.productModule==='机器人数据库'?window.showProducts():openModule(b.dataset.productModule));
let query='';
function render(){sub.querySelectorAll('[data-product-module]').forEach(b=>b.classList.toggle('selected',b.dataset.productModule===(location.hash==='#products/manufacturers'?'厂商档案':location.hash==='#products/compare'?'产品对比':location.hash==='#products/rankings'?'机器人榜单':'机器人数据库')));if(location.hash==='#products/manufacturers'&&window.renderManufacturers){window.renderManufacturers(view);return}if(location.hash==='#products/compare'&&window.renderCompare){window.renderCompare(view);return}if(location.hash==='#products/rankings'&&window.renderRankings){window.renderRankings(view);return}if((location.hash==='#products/hand'||location.hash.startsWith('#products/hand/'))&&window.renderHandPage){window.renderHandPage(view);return}const key=location.hash.split('/')[1];const item=items.find(i=>i[0]===key);view.innerHTML=item?`<a class="product-back" href="#products">← 返回全部分类</a><div class="product-detail"><div class="category-icon">${icon(item[4])}</div><p class="eyebrow">${item[2]}</p><h1>${item[1]==='全部'?'全部机器人':item[1]}</h1><p>${item[3]}</p><div class="product-pending"><h2>典型产品即将收录</h2><p>这里将展示${item[1]==='全部'?'各类机器人':item[1]}的典型产品。</p><a href="#products">继续浏览分类 →</a></div></div>`:`<section class="product-heading"><p class="eyebrow">ROBOT GALAXY / DATABASE</p><h1>从形态出发，认识机器人<span>。</span></h1><p>选择一个类别，探索机器人产品。</p></section><div class="section-heading"><h2><i></i>机器人数据库 <span>CATEGORIES</span></h2><span>7 大类别</span></div><div class="category-grid">${items.filter(i=>i.slice(1,4).join(' ').toLowerCase().includes(query.toLowerCase())).map((i,n)=>`<a class="category-card ${i[0]==='all'?'category-all':''}" href="#products/${i[0]}" style="--icon-hue:${[210,200,220,185,230,205,175,215][n]}"><div class="category-card-top"><span class="category-icon">${icon(i[4])}</span><span class="category-arrow">↗</span></div><p class="category-english">${i[2]}</p><h3>${i[1]}</h3><p class="category-description">${i[3]}</p><span class="category-enter">查看分类 <span>→</span></span></a>`).join('')}</div>`;if(!item&&!view.querySelector('.category-card'))view.insertAdjacentHTML('beforeend','<div class="empty"><h3>暂无匹配的分类</h3><p>试试“人形”“灵巧手”或清空搜索。</p></div>')}
function route(){const active=location.hash==='#products'||location.hash.startsWith('#products/');view.hidden=!active;sub.hidden=!active;document.querySelector('header>.subnav:not(.product-subnav)').hidden=active;if(active){['news-view','reports-view','events-view'].forEach(id=>$(id).hidden=true);document.querySelectorAll('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module==='产品'));$('search').placeholder='搜索机器人类别';$('search').setAttribute('aria-label','搜索机器人类别');$('search').value=query;render()}}
window.showProducts=()=>{location.hash='products';route()};window.addEventListener('hashchange',route);$('search').addEventListener('input',x=>{if(!view.hidden){if(location.hash==='#products/manufacturers'||location.hash==='#products/compare'||location.hash==='#products/rankings'||location.hash==='#products/hand'||location.hash.startsWith('#products/hand/'))return;query=x.target.value.trim();if(location.hash!=='#products')location.hash='products';render()}});route();
})();
