(()=>{
const esc=escapeHtml,$=id=>document.getElementById(id);
const cats=['全部','人形','轮式','四足','履带','复合','灵巧手','协作臂'];
const scenes=['全部','工业制造','商用服务','科研教育','家庭服务','农业服务','特种作业','医疗健康','养老服务'];
const axes=['自由度','重量','体积','重复定位精度','速度','抓握力'];
let mode='products',keywordDemo=false;
let rows=[],status='loading',host,state={cat:'全部',scene:'全部',period:'月榜',metric:'综合',query:''};
const samples=[[7,8,8,9,7,8],[7,7,7,9,8,9],[7,9,8,8,8,8],[7,9,8,8,9,7],[8,7,7,9,8,8],[10,9,9,7,9,8],[9,7,7,8,8,8],[10,5,5,8,8,9],[7,8,8,9,7,9],[10,6,6,9,8,10]];
window.homeRanking=()=>[...rows].sort((a,b)=>b.scores.reduce((s,n)=>s+n,0)-a.scores.reduce((s,n)=>s+n,0)||a.order-b.order)[0];
const active=()=>location.hash==='#products/rankings';
const href=p=>'#products/hand/'+p.id;
const score=p=>state.metric==='综合'?p.scores.reduce((a,b)=>a+b,0)/6:p.scores[axes.indexOf(state.metric)];
const periodLabel=()=>({'月榜':'2026 年 9 月','季榜':'2026 年第三季度','年度榜':'2026 年度','新品榜':'新品观察'})[state.period];
const result=()=>rows.filter(p=>(state.cat==='全部'||state.cat==='灵巧手')&&(state.scene==='全部'||p.demoScenes.includes(state.scene))&&[p.model,p.maker].join(' ').toLowerCase().includes(state.query.toLowerCase())).sort((a,b)=>score(b)-score(a)||a.order-b.order);
function chips(key,title,list){return `<div class="rank-filter" role="group" aria-label="${title}"><span>${title}</span><div>${list.map(v=>`<button data-rank-key="${key}" data-value="${v}" aria-pressed="${state[key]===v}">${v}</button>`).join('')}</div></div>`}
function radar(p){const pt=(i,r)=>[130+Math.sin(i*Math.PI/3)*r,115-Math.cos(i*Math.PI/3)*r];return `<svg class="rank-radar" viewBox="0 0 260 240" role="img" aria-label="${esc(p.model)}示例六维评分">${[20,40,60,80].map(r=>`<polygon points="${axes.map((_,i)=>pt(i,r).join(',')).join(' ')}" fill="none" stroke="#294564"/>`).join('')}${axes.map((a,i)=>{const [x,y]=pt(i,103);return `<text x="${x}" y="${y+4}" text-anchor="middle" fill="#9aafce" font-size="11">${a}</text>`}).join('')}<polygon points="${p.scores.map((s,i)=>pt(i,s*8).join(',')).join(' ')}" fill="#69a8ff33" stroke="#80b4ff" stroke-width="2"/></svg>`}
function display(){if(!active())return;if(mode==='keywords'){renderKeywords();return}host.innerHTML=`${modeTabs()}<section class="rank-hero"><div><p class="eyebrow">ROBOT GALAXY / RANKINGS</p><h1>发现值得关注的<br>机器人<span>。</span></h1><p>按周期发现好产品，按品类找到你的关注。</p></div><div class="rank-orbit" aria-hidden="true"><div>RG<span>ROBOT INDEX</span></div><b>01</b><i>02</i><em>03</em></div></section><div class="rank-notice"><strong>榜单演示版</strong><span>当前收录 10 款灵巧手。分数为布局演示，不代表实测、真实口碑或采购建议。</span></div><section class="rank-controls"><div class="rank-periods" role="group" aria-label="榜单周期">${['月榜','季榜','年度榜','新品榜'].map(x=>`<button data-rank-key="period" data-value="${x}" aria-pressed="${state.period===x}">${x}</button>`).join('')}<span>${periodLabel()} · 演示快照</span></div>${chips('cat','品类',cats)}<div class="rank-search"><input id="rank-search" aria-label="搜索榜单产品" type="search" placeholder="搜索产品或厂家" value="${esc(state.query)}"><button id="rank-reset">重置筛选</button></div></section><div class="rank-layout"><section><div class="rank-section-head"><div><p class="eyebrow">THE ROBOT SHORTLIST</p><h2 id="rank-title"></h2></div><span id="rank-count" aria-live="polite"></span></div><div id="rank-content"></div></section><aside><section class="rank-method"><span class="eyebrow">HOW IT WORKS</span><h2>看懂这张榜单</h2><ol><li><b>先选周期</b><p>选择月榜、季榜、年度榜或新品榜。</p></li><li><b>再选品类</b><p>按机器人品类查看榜单。当前按六项示例评分的平均分排序，同分按收录顺序。</p></li><li><b>回到产品</b><p>查看原厂参数、资料来源和产品详情，继续了解具体型号。</p></li></ol><div class="rank-method-note">各周期目前共用同一演示样本，不代表历史榜单；新品页不表示产品实际上市时间。不同品类尚未建立统一评分标准。</div></section><section class="rank-library"><span>DATABASE ↗</span><h2>榜单是起点，<br>参数里见细节。</h2><p>查看灵巧手图片、规格与各型号配置。</p><a href="#products/hand">进入灵巧手产品库 →</a></section></aside></div>`;
bindModes();host.querySelectorAll('[data-rank-key]').forEach(b=>b.onclick=()=>{state[b.dataset.rankKey]=b.dataset.value;display()});$('rank-search').oninput=e=>{state.query=e.target.value;$('search').value=state.query;renderResults()};$('rank-reset').onclick=()=>{state={cat:'全部',scene:'全部',period:'月榜',metric:'综合',query:''};display()};$('search').placeholder='搜索榜单产品';$('search').setAttribute('aria-label','搜索榜单产品');$('search').value=state.query;renderResults()}
function renderResults(){const found=result();$('rank-title').textContent=`${state.cat==='全部'?'机器人':state.cat} · ${state.metric==='综合'?'综合':state.metric}${state.period}`;$('rank-count').textContent=found.length+' 款 · 示例排序';if(status!=='ready'){$('rank-content').innerHTML=`<div class="rank-empty"><h3>${status==='loading'?'正在读取榜单…':'榜单资料暂时无法加载'}</h3>${status==='failed'?'<button id="rank-retry">重新加载</button>':''}</div>`;$('rank-retry')?.addEventListener('click',load);return}if(!found.length){$('rank-content').innerHTML=`<div class="rank-empty"><span>◎</span><h3>${state.cat!=='全部'&&state.cat!=='灵巧手'?'这个品类正在等待收录':'暂无符合条件的演示产品'}</h3><p>当前榜单仅含灵巧手样本，后续再接入更多品类及经核验的场景数据。</p><button id="rank-empty-reset">查看全部演示榜单</button><a href="#products">探索机器人数据库 →</a></div>`;$('rank-empty-reset').onclick=()=>$('rank-reset').click();return}
const first=found[0];$('rank-content').innerHTML=`<article class="rank-feature"><div class="rank-feature-heading"><span>NO. 01 / ${state.metric}榜</span><small>示例评分</small></div><div class="rank-feature-body"><a href="${href(first)}" class="rank-feature-image"><img src="${esc(first.image)}" alt="${esc(first.model)}"></a><div><p>${esc(first.maker)}</p><h3><a href="${href(first)}">${esc(first.model)}</a></h3><div class="rank-big-score">${score(first).toFixed(1)}<small>/10</small></div><span class="rank-spec-line">${esc(first.dofText)} · ${esc(first.weightText)}</span><a class="rank-detail" href="${href(first)}">查看产品详情 ↗</a></div>${radar(first)}</div></article><div class="rank-list-head"><span>排名 / 产品</span><span>${state.metric}示例分</span></div><div class="rank-rows">${found.map((p,i)=>`<article class="rank-row"><strong class="rank-position ${i<3?'rank-leading':''}">${String(i+1).padStart(2,'0')}</strong><a class="rank-thumb" href="${href(p)}"><img src="${esc(p.image)}" alt="${esc(p.model)}" loading="lazy"></a><div class="rank-row-info"><span>${esc(p.maker)}</span><h3><a href="${href(p)}">${esc(p.model)}</a></h3><p>${esc(p.dofText)} · ${esc(p.weightText)}</p><div class="rank-mini-scores">${axes.map((a,n)=>`<span class="${state.metric===a?'chosen':''}">${a} <b>${p.scores[n]}</b></span>`).join('')}</div></div><div class="rank-row-score"><strong>${score(p).toFixed(1)}</strong><span>示例 / 10</span><a href="${href(p)}">详情 ↗</a></div></article>`).join('')}</div><p class="rank-bottom-note">榜单分数独立于详情页的本机体验评分，暂不汇总用户评价。重量、体积得分越高表示越轻巧；其余维度得分越高表示示例评价越好。</p>`}

function modeTabs(){return `<nav class="rank-mode-tabs" aria-label="榜单类型"><button data-rank-mode="products" aria-pressed="${mode==='products'}">机器人榜单</button><button data-rank-mode="keywords" aria-pressed="${mode==='keywords'}">关键词热榜 <span>DAILY</span></button></nav>`}
function bindModes(){host.querySelectorAll('[data-rank-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.rankMode;display()})}
function renderKeywords(){const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date());const words=['具身智能','人形机器人','灵巧手','宇树机器人','机器人世界模型','机器人进厂','协作机器人','机器人数据采集'];host.innerHTML=`${modeTabs()}<section class="rank-hero"><div><p class="eyebrow">ROBOT GALAXY / SEARCH TRENDS</p><h1>机器人行业，<br>今天大家在搜什么<span>？</span></h1><p>关注中国机器人行业的搜索趋势与关键词变化。</p></div><div class="keyword-date"><span>北京时间 · 今日</span><strong>${today}</strong><small>每日关键词观察</small></div></section><div class="rank-notice"><strong>${keywordDemo?'示例预览 · 非真实热榜':'今日数据待接入'}</strong><span>${keywordDemo?'以下词条、指数、涨幅和趋势均为虚构演示，不代表当天搜索排名。':'尚无可核验的当日搜索指数，暂不展示真实排名、搜索量或涨幅。'}</span></div><div class="keyword-toolbar"><span>统计范围：中国 · 机器人行业<br><small>来源：待接入　｜　数据更新时间：暂无</small></span><button id="keyword-demo" aria-pressed="${keywordDemo}">${keywordDemo?'返回真实数据状态':'预览示例榜单'}</button></div><div class="rank-layout"><section>${keywordDemo?`<div class="keyword-table-heading"><span>关键词 / 示例排名</span><span>示例指数 / 日变化</span></div>${words.map((w,i)=>`<article class="keyword-row"><strong>${String(i+1).padStart(2,'0')}</strong><div><h3>${w}</h3><span>演示词条 · 非今日真实排名</span></div><svg viewBox="0 0 100 35" aria-label="虚构趋势示意"><path d="M0 29L14 21L28 ${23-i}L42 25L56 ${15+i}L70 17L84 9L100 ${5+i}" fill="none" stroke="#70b7cf" stroke-width="2"/></svg><div class="keyword-value"><b>${(9800-i*870).toLocaleString()}</b><span>+${(32.4-i*3.1).toFixed(1)}% 示例</span></div></article>`).join('')}`:`<div class="rank-empty keyword-pending"><span>⌕</span><h3>等待今日搜索数据</h3><p>接入可用的数据源后，这里将展示关键词排名、搜索指数、日变化与趋势。</p><p>搜索指数不是实际搜索次数；单一平台指数也不等于中国全网搜索量。</p></div>`}</section><aside><section class="rank-method"><p class="eyebrow">DATA & SOURCES</p><h2>热榜怎么产生？</h2><ol><li><b>明确数据范围</b><p>按具体搜索平台、日期与机器人关键词池统计，展示来源与更新时间。</p></li><li><b>按同口径排序</b><p>同一来源的搜索指数降序排列；不同平台不直接相加。当前未接入任何指数数据。</p></li><li><b>不混淆新闻热度</b><p>媒体报道数量可以衡量报道热度，但不能作为搜索量。</p></li></ol><a class="rank-detail" href="https://index.baidu.com/Helper" target="_blank" rel="noopener noreferrer">了解百度指数口径 ↗</a></section></aside></div>`;bindModes();$('keyword-demo').onclick=()=>{keywordDemo=!keywordDemo;renderKeywords()};$('search').value='';$('search').placeholder='切换机器人榜单后搜索产品';}

async function load(){status='loading';if(host&&active())display();try{const r=await fetch('hands/catalog.json',{cache:'no-cache'});if(!r.ok)throw Error();rows=(await r.json()).filter(p=>p.representative).map((p,i)=>({...p,order:i,scores:samples[i]||[7,7,7,7,7,7],demoScenes:i%3===0?['科研教育','工业制造']:i%3===1?['工业制造']:['科研教育']}));status='ready'}catch{status='failed'}if(host&&active())display()}
window.renderRankings=el=>{host=el;display()};window.showRankings=()=>{location.hash='products/rankings';if(active()&&host)display()};$('search').addEventListener('input',e=>{if(active()&&mode==='products'){state.query=e.target.value;$('rank-search').value=state.query;renderResults()}});load();if(active()){host=$('products-view');display()}
})();
