(()=>{
const $=id=>document.getElementById(id), esc=escapeHtml;
window.homeReport=()=>catalog[0];
let catalog=[],companyList=[],s={category:'全部',company:'全部',query:'',limit:8};
const view=document.createElement('main');view.id='reports-view';view.className='wrap';view.hidden=true;
view.innerHTML=`<section class="heading"><div><p class="eyebrow">THE GALAXY RESEARCH ／ 产业知识库</p><h1>看见产业背后的逻辑<span>。</span></h1><p>从本体到核心零部件，连接报告、公司与技术脉络。</p></div><div class="research-stamp">RESEARCH LIBRARY<strong id="library-total">—</strong><span>研报与资料 · 本地导入</span></div></section><div class="section-heading"><h2><i></i>机器人研报 <span>RESEARCH</span></h2><button id="report-reset">重置筛选</button></div><section class="filters report-filters"><div class="filter-row" id="report-categories"><span>类别</span></div><div class="filter-row" id="report-companies"><span>公司</span></div><button id="expand-companies">展开更多公司 ＋</button><div class="report-search-row"><input type="search" id="report-search" aria-label="检索研报" placeholder="搜索研报标题、摘要、机构、公司或关键词"><span>多维筛选，找到所需研究</span></div></section><div class="feed-toolbar"><strong id="report-count" aria-live="polite"></strong><span>按报告日期排序 · 未注明日期的资料置后</span></div><div id="report-list" aria-live="polite">正在读取研报目录…</div><button class="more" id="report-more">查看更多研报 ＋</button><p class="source-note report-source">基于上传文件整理，摘要不替代原报告。公司筛选结合正文提及与原文件夹归档；资料链接单独标注。当前未接入自动采集。</p>`;
const news=document.querySelector('main');news.id='news-view';news.after(view);
function route(){const active=location.hash==='#reports';news.hidden=location.hash!=='#news';view.hidden=!active;document.querySelectorAll('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module===(['#reports','#news','#events'].includes(location.hash)?'资讯':'首页')));document.querySelectorAll('[data-channel]').forEach(b=>b.classList.toggle('selected',b.dataset.channel===(active?'机器人研报':'机器人资讯')));$('search').placeholder=active?'搜索研报、机构、公司':'搜索资讯、公司、关键词';$('search').setAttribute('aria-label',active?'搜索研报':'搜索资讯');$('search').value=active?s.query:state.query;}
window.showReports=()=>{location.hash='reports';route()};window.showNews=()=>{location.hash='news';route()};window.addEventListener('hashchange',route);route();
function chips(id,items,key){$(id).innerHTML='<span>'+ (key==='category'?'类别':'公司')+'</span>';items.forEach(label=>{const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-pressed',label===s[key]);b.classList.toggle('active',label===s[key]);b.onclick=()=>{s[key]=label;s.limit=8;refreshChips();renderReports()};$(id).append(b)})}
function refreshChips(){chips('report-categories',categories,'category');chips('report-companies',['全部',...companyList],'company')}
function renderReports(){const found=catalog.filter(r=>(s.category==='全部'||r.categories.includes(s.category))&&(s.company==='全部'||[...r.companies,...r.collections].includes(s.company))&&[r.title,r.summary,r.institution,r.filename,...r.companies,...r.collections,...r.categories].join(' ').toLowerCase().includes(s.query.toLowerCase()));$('report-count').textContent=`找到 ${found.length} 份研报与资料`;$('report-list').innerHTML=found.length?found.slice(0,s.limit).map(r=>`<article class="report-card"><a class="report-cover" href="${esc(r.file||r.url)}" target="_blank" rel="noopener noreferrer" aria-label="阅读 ${esc(r.title)}">${r.cover?`<img src="${esc(r.cover)}" alt="${esc(r.title)}封面" loading="lazy">`:`<div class="document-placeholder"><span>ROBOT GALAXY</span><strong>${r.format==='URL'?'↗':'PPTX'}</strong><small>${r.format==='URL'?'外部资料':'研究资料'}</small></div>`}</a><div class="report-body"><div class="news-tags">${r.categories.map(c=>`<span>${esc(c)}</span>`).join('')}<span>${r.format==='URL'?'资料链接':esc(r.format)+(r.pages?' · '+r.pages+' 页':'')}</span></div><h3><a href="${esc(r.file||r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a></h3><div class="report-institution">${esc(r.institution)} <span>· ${esc(r.date||r.period&&r.period+' 年（具体日期未注明）'||'日期未注明')}</span></div><p>${esc(r.summary)}</p><div class="report-mentions">${r.companies.length?'提及公司：'+esc(r.companies.join('、')):r.collections.length?'原归档：'+esc(r.collections.join('、')):'提及公司：暂未识别'}</div>${r.note?`<small class="report-note">${esc(r.note)}</small>`:''}<div class="report-actions"><span title="${esc(r.filename)}">原文件：${esc(r.filename)}</span><a href="${esc(r.file||r.url)}" target="_blank" rel="noopener noreferrer">${r.format==='URL'?'打开原资料 ↗':r.format==='PPTX'?'下载演示资料 ↓':'阅读原报告 ↗'}</a>${r.file?`<a href="${esc(r.file)}" download="${esc(r.filename)}">下载 ↓</a>`:''}</div></div></article>`).join(''):`<div class="empty"><h3>${s.company==='专家访谈'?'暂未收录专家访谈':'暂无符合条件的研报'}</h3><p>可以调整类别、公司或关键词，再试一次。</p><button id="report-empty-reset">清除筛选</button></div>`;$('report-more').hidden=found.length<=s.limit;$('report-empty-reset')?.addEventListener('click',resetReports)}
function resetReports(){s={category:'全部',company:'全部',query:'',limit:8};$('report-search').value='';$('search').value='';refreshChips();renderReports()}
$('report-reset').onclick=resetReports;$('report-more').onclick=()=>{s.limit+=8;renderReports()};$('expand-companies').onclick=()=>{const expanded=$('report-companies').classList.toggle('expanded');$('expand-companies').textContent=expanded?'收起公司 −':'展开更多公司 ＋';$('expand-companies').setAttribute('aria-expanded',expanded)};
function search(value){s.query=value.trim();s.limit=8;$('report-search').value=value;$('search').value=value;renderReports()}
$('report-search').oninput=e=>search(e.target.value);$('search').addEventListener('input',e=>{if(!view.hidden)search(e.target.value)});
fetch('reports/catalog.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{catalog=data.records.sort((a,b)=>(b.date||'').localeCompare(a.date||''));companyList=data.companies;$('library-total').textContent=catalog.length;refreshChips();renderReports()}).catch(()=>{$('report-list').textContent='研报目录暂时无法读取，请刷新页面重试。'});
})();
