(()=>{
const $=id=>document.getElementById(id),esc=escapeHtml,categories=['全部','人形','轮式','四足','履带','复合','灵巧手','协作臂'];
const records=[
{cat:'人形',type:'开箱实测',model:'Unitree G1',author:'马杰思',date:'2025-03-14',title:'〖开箱〗抢到啦！宇树机器人实测',summary:'围绕宇树 G1 普通版展开开箱和初步体验，了解消费端拿到机器人后的基本使用感受与功能边界。',focus:['开箱体验','基础功能','使用感受'],url:'https://www.bilibili.com/video/BV1xzQ6YFERD/'},
{cat:'四足',type:'媒体现场体验',model:'CyberDog 2',author:'甲子光年',date:'2023-08-15',title:'现场实测，小米CyberDog2有多“狗”',summary:'科技媒体带来的 CyberDog 2 现场实测入口，适合直观看看这款仿生四足机器人的现场表现。',focus:['四足机器人','现场体验','仿生交互'],url:'https://www.bilibili.com/video/BV1Wr4y1d76r/'},
{cat:'轮式',type:'科技媒体体验',model:'米家全能扫拖机器人 2',author:'微机分WekiHome',date:'2023-08-13',title:'太卷了，2000 元档也开始玩全能扫拖一体基站了？',summary:'围绕米家全能扫拖机器人 2 与一体基站展开体验，从家庭清洁需求出发了解产品。标题价格为发布时背景。',focus:['家庭清洁','一体基站','产品体验'],url:'https://www.bilibili.com/list/347441270?bvid=BV1c8411d7ix&oid=232243632'},
{cat:'轮式',type:'真实环境体验',model:'米家全能扫拖机器人',author:'随意评测',date:'2022-05-03',title:'〖新品开箱〗米家全能扫拖机器人开箱体验+超真实环境评测',summary:'结合开箱与实际清洁环境分享体验，作者简介提及加水频率和产品仍待打磨之处，适合关注日常使用细节。',focus:['环境测试','清洁体验','维护使用'],url:'https://www.bilibili.com/video/BV1F3411T72s/'}
];
window.homeReview=()=>records[0];
records.forEach((r,i)=>{r.image='reviews/'+['g1','dog','mijia2','mijia'][i]+'.jpg';r.format='video';r.platform='B站'});
const articles=[
{image:'g30',cat:'轮式',model:'石头 G30',author:'IT之家 · 马卡',date:'2025-01-08',title:'石头自清洁扫拖机器人 G30 体验：升降雷达，升降地盘，家居清洁的「硬派 SUV」',summary:'从升降雷达与底盘切入，体验低矮家具下的清洁与越障表现，并关注扫拖功能。',focus:['升降雷达','越障','家庭清洁'],url:'https://www.ithome.com/0/823/232.htm'},
{image:'space',cat:'复合',model:'石头 G30 Space 探索版',author:'IT之家 · 马卡',date:'2025-02-26',title:'机械手第一次走进家庭：石头自清洁扫拖机器人 G30 Space 探索版深度体验',summary:'关注带机械手的扫拖机器人，结合实际使用体验讨论拾取物品、清洁和越障。按移动底盘加操作机构归入复合类。',focus:['机械手','移动操作','清洁体验'],url:'https://www.ithome.com/0/833/872.htm'},
{image:'g20',cat:'轮式',model:'石头 G20',author:'IT之家 · 汐元',date:'2023-04-03',title:'石头自清洁扫拖机器人 G20 体验：可以更彻底的做个“懒人”了',summary:'从外观、基站到吸尘与擦地进行体验，包含咖啡粉、食物残渣以及模拟毛发的清扫测试。',focus:['双胶刷','吸尘测试','擦地'],url:'https://www.ithome.com/0/684/102.htm'},
{image:'t8',cat:'轮式',model:'石头 T8 智能集尘版',author:'IT之家 · 汐元',date:'2022-03-17',title:'石头扫地机器人 T8 智能集尘版体验：性价比之选，让你忘掉倒垃圾',summary:'围绕扫拖机器人与集尘座套装展开上手，了解自动集尘、机身设计及日常清洁体验。',focus:['自动集尘','上手体验','清洁'],url:'https://www.ithome.com/0/608/192.htm'},
{image:'t7',cat:'轮式',model:'石头 T7',author:'IT之家 · 马卡',date:'2020-03-23',title:'石头扫地机器人 T7 评测：目前石头科技最好用的扫地机器人',summary:'结合当时的长期体验，介绍电控水箱、清洁功能与地图管理。标题中的“目前”指原文发布时期。',focus:['电控水箱','地图管理','历史评测'],url:'https://www.ithome.com/0/479/148.htm'}
].map(r=>({...r,image:'reviews/'+r.image+'.jpg',format:'article',type:'图文评测',platform:'IT之家'}));
let category='全部',query='';const view=document.createElement('main');view.id='reviews-view';view.className='wrap';view.hidden=true;$('products-view').after(view);
function render(){view.innerHTML=`<section class="review-heading"><div><p class="eyebrow">ROBOT GALAXY / REVIEWS</p><h1>参数之外，<br>看看真实表现<span>。</span></h1><p>汇集中文机器人测评与体验，回到实际使用现场。</p></div><div class="review-stamp"><strong>09</strong><span>4 条视频 · 5 篇文章</span><small>WATCH / READ</small></div></section><div class="review-categories" role="group" aria-label="测评分类">${categories.map(c=>`<button data-review-cat="${c}" aria-pressed="${category===c}">${c}</button>`).join('')}</div><div class="review-tools"><input id="review-search" aria-label="搜索测评" type="search" placeholder="搜索产品、作者或测评关键词" value="${esc(query)}"><span id="review-count" aria-live="polite"></span></div><div class="review-split"><section><div class="review-column-heading"><h2>视频测评 <small>WATCH</small></h2><span id="review-video-count"></span></div><div id="review-results" aria-live="polite"></div></section><section><div class="review-column-heading"><h2>文章测评 <small>READ</small></h2><span id="review-article-count"></span></div><div id="review-articles" aria-live="polite"></div></section></div><p class="review-foot">封面与配图来自对应原页面，版权与观点归原作者。视频摘要依据标题与简介整理，文章摘要依据原文整理；较早内容中的价格、软件与产品版本请以原文时间为准。</p>`;view.querySelectorAll('[data-review-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.reviewCat;render()});$('review-search').oninput=e=>{query=e.target.value;$('search').value=query;renderCards()};renderCards()}
function renderCards(){const match=r=>(category==='全部'||r.cat===category)&&[r.title,r.model,r.author,r.summary,...r.focus].join(' ').toLowerCase().includes(query.trim().toLowerCase());const videos=records.filter(match),texts=articles.filter(match);$('review-count').textContent=`${videos.length} 条视频 · ${texts.length} 篇文章`;$('review-video-count').textContent=videos.length+' 条';$('review-article-count').textContent=texts.length+' 篇';const card=r=>`<article class="review-card"><a class="review-photo" href="${r.url}" target="_blank" rel="noopener noreferrer" aria-label="${r.format==='video'?'观看':'阅读'}：${esc(r.title)}"><img src="${r.image}" alt="${esc(r.model)} ${r.format==='video'?'视频封面':'原文配图'}" loading="lazy"><span class="review-photo-badge">${r.format==='video'?'▶ 视频':'▤ 文章'} · ${r.platform}</span><span class="review-image-fallback" hidden>${esc(r.model)} · 查看原文配图 ↗</span></a><div class="review-copy"><div class="review-labels"><span>${r.cat}</span><span>${r.type}</span></div><h2><a href="${r.url}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a></h2><p>${esc(r.summary)}</p><div class="review-focus">${r.focus.map(t=>`<span># ${t}</span>`).join('')}</div><div class="review-meta"><span>${r.author} · ${r.date}</span><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.format==='video'?'去 B 站观看':'阅读全文'} ↗</a></div></div></article>`;const empty=kind=>`<div class="review-empty"><h2>暂无匹配的${kind}</h2><p>试试其他分类或关键词。</p><button data-review-reset>查看全部内容</button></div>`;$('review-results').innerHTML=videos.length?videos.map(card).join(''):empty('视频');$('review-articles').innerHTML=texts.length?texts.map(card).join(''):empty('文章');view.querySelectorAll('[data-review-reset]').forEach(b=>b.onclick=()=>{category='全部';query='';$('search').value='';render()});view.querySelectorAll('.review-photo img').forEach(img=>{img.onerror=()=>{img.hidden=true;img.parentElement.querySelector('.review-image-fallback').hidden=false}})}
function route(){const active=location.hash==='#reviews';view.hidden=!active;if(active){['news-view','reports-view','events-view','products-view'].forEach(id=>$(id).hidden=true);document.querySelectorAll('header>.subnav').forEach(n=>n.hidden=true);document.querySelectorAll('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module==='测评'));$('search').placeholder='搜索测评、产品或作者';$('search').setAttribute('aria-label','搜索测评');$('search').value=query;render()}}
window.showReviews=()=>{location.hash='reviews';route()};window.addEventListener('hashchange',route);$('search').addEventListener('input',e=>{if(!view.hidden){query=e.target.value;$('review-search').value=query;renderCards()}});route();
})();
